#!/usr/bin/env node
var cp = require('./utils/child-process-wrapper.js');
process.chdir(require('path').dirname(__dirname));

cp.safeSpawnP("npm", ["install"], {cwd: "./build"}).then(function(){
  return cp.safeSpawnP("npm", ["install"]);
}).then(function(){
  return cp.safeSpawnP("node_modules/.bin/electron-rebuild");
}).then(function(){
  return process.exit(0);
}).catch(function(err){
  console.error(err.message);
  console.error(err.stack);
  process.exit(1);
});
